# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_version_three.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto_version_three.proto\"*\n\x14OptionalMessageThree\x12\x12\n\ncoder_name\x18\x01 \x01(\t\"+\n\x14RepeatedMessageThree\x12\x13\n\x0b\x63oder_names\x18\x01 \x03(\t\"I\n\x11OneOfMessageThree\x12\x13\n\tfull_name\x18\x01 \x01(\tH\x00\x12\x14\n\nfirst_name\x18\x02 \x01(\tH\x00\x42\t\n\x07\x61ny_one\"L\n\x14ReservedMessageThree\x12\x0f\n\x07my_name\x18\x04 \x01(\tJ\x04\x08\x01\x10\x04J\x04\x08\x05\x10\x06R\ncoder_nameR\x0b\x63oder_namesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_version_three_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPTIONALMESSAGETHREE._serialized_start=29
  _OPTIONALMESSAGETHREE._serialized_end=71
  _REPEATEDMESSAGETHREE._serialized_start=73
  _REPEATEDMESSAGETHREE._serialized_end=116
  _ONEOFMESSAGETHREE._serialized_start=118
  _ONEOFMESSAGETHREE._serialized_end=191
  _RESERVEDMESSAGETHREE._serialized_start=193
  _RESERVEDMESSAGETHREE._serialized_end=269
# @@protoc_insertion_point(module_scope)
