# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_version_two.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto_version_two.proto\"%\n\x0fRequiredMessage\x12\x12\n\ncoder_name\x18\x01 \x02(\t\"%\n\x0fOptionalMessage\x12\x12\n\ncoder_name\x18\x01 \x01(\t\"&\n\x0fRepeatedMessage\x12\x13\n\x0b\x63oder_names\x18\x01 \x03(\t\"D\n\x0cOneOfMessage\x12\x13\n\tfull_name\x18\x01 \x01(\tH\x00\x12\x14\n\nfirst_name\x18\x02 \x01(\tH\x00\x42\t\n\x07\x61ny_one')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_version_two_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUIREDMESSAGE._serialized_start=27
  _REQUIREDMESSAGE._serialized_end=64
  _OPTIONALMESSAGE._serialized_start=66
  _OPTIONALMESSAGE._serialized_end=103
  _REPEATEDMESSAGE._serialized_start=105
  _REPEATEDMESSAGE._serialized_end=143
  _ONEOFMESSAGE._serialized_start=145
  _ONEOFMESSAGE._serialized_end=213
# @@protoc_insertion_point(module_scope)
