# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: first_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66irst_message.proto\"W\n\x0c\x46irstMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x1e\n\x08msg_type\x18\x04 \x01(\x0e\x32\x0c.MessageType*t\n\x0bMessageType\x12\x18\n\x14MESSAGE_TYPE_INVALID\x10\x00\x12\x16\n\x12MESSAGE_TYPE_UNSET\x10\x01\x12\x1a\n\x16MESSAGE_TYPE_EMERGENCY\x10\x02\x12\x17\n\x13MESSAGE_TYPE_UPDATE\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'first_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._serialized_start=112
  _MESSAGETYPE._serialized_end=228
  _FIRSTMESSAGE._serialized_start=23
  _FIRSTMESSAGE._serialized_end=110
# @@protoc_insertion_point(module_scope)
