# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basics_two.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61sics_two.proto\"\xfc\x01\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12 \n\x07\x63ontact\x18\x04 \x01(\x0b\x32\x0f.Person.Contact\x12\'\n\x0bperson_type\x18\x05 \x01(\x0e\x32\x12.Person.PersonType\x1a&\n\x07\x43ontact\x12\x0c\n\x04mail\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\"X\n\nPersonType\x12\x15\n\x11PERSON_TYPE_UNSET\x10\x00\x12\x16\n\x12PERSON_TYPE_LEGEND\x10\x01\x12\x1b\n\x17PERSON_TYPE_ULTRALEGEND\x10\x02\"R\n\x08\x45mployee\x12\x0e\n\x06\x65mp_id\x18\x01 \x01(\x05\x12\x10\n\x08\x65mp_name\x18\x02 \x01(\t\x12$\n\x0b\x65mp_contact\x18\x03 \x01(\x0b\x32\x0f.Person.Contactb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basics_two_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON._serialized_start=21
  _PERSON._serialized_end=273
  _PERSON_CONTACT._serialized_start=145
  _PERSON_CONTACT._serialized_end=183
  _PERSON_PERSONTYPE._serialized_start=185
  _PERSON_PERSONTYPE._serialized_end=273
  _EMPLOYEE._serialized_start=275
  _EMPLOYEE._serialized_end=357
# @@protoc_insertion_point(module_scope)
