# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csimple.proto\x12\x10mypackage.simple*V\n\x07MyColor\x12\x12\n\x0eMY_COLOR_UNSET\x10\x00\x12\x10\n\x0cMY_COLOR_RED\x10\x01\x12\x12\n\x0eMY_COLOR_GREEN\x10\x02\x12\x11\n\rMY_COLOR_BLUE\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simple_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MYCOLOR._serialized_start=34
  _MYCOLOR._serialized_end=120
# @@protoc_insertion_point(module_scope)
